# Generated by Django 3.1.14 on 2023-09-07 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='title',
        ),
    ]
